include: package:lints/recommended.yaml

analyzer:
  errors:
    depend_on_referenced_packages: ignore
    invalid_use_of_visible_for_testing_member: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "example/**"

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_extensions
    - curly_braces_in_flow_control_structures
    - depend_on_referenced_packages
    - directives_ordering
    - empty_catches
    - file_names
    - hash_and_equals
    - no_duplicate_case_values
    - non_constant_identifier_names
    - package_prefixed_library_names
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - public_member_api_docs
    - recursive_getters
    - slash_for_doc_comments
    - sort_constructors_first
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps
