// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:convert';

import 'package:collection/collection.dart';
import 'package:meta/meta.dart';

/// Represents a single analytics event parameter.
@immutable
final class AnalyticsParameter {
  /// Creates a new analytics parameter.
  const AnalyticsParameter({
    String? codeName,
    required this.name,
    this.sourceName,
    required this.type,
    required this.isNullable,
    this.description,
    this.allowedValues,
    this.regex,
    this.minLength,
    this.maxLength,
    this.min,
    this.max,
    this.meta = const {},
    this.operations,
    this.addedIn,
    this.deprecatedIn,
  }) : codeName = codeName ?? name;

  /// Analytics key that gets sent to providers.
  final String name;

  /// The original key in the YAML file (if different from name).
  final String? sourceName;

  /// Identifier used when generating Dart API (defaults to [name]).
  final String codeName;

  /// The Dart type of the parameter.
  final String type;

  /// Whether the parameter is nullable.
  final bool isNullable;

  /// Optional description of the parameter.
  final String? description;

  /// Optional list of allowed values.
  final List<dynamic>? allowedValues;

  /// Regex pattern for validation.
  final String? regex;

  /// Minimum length for string parameters.
  final int? minLength;

  /// Maximum length for string parameters.
  final int? maxLength;

  /// Minimum value for numeric parameters.
  final num? min;

  /// Maximum value for numeric parameters.
  final num? max;

  /// Custom metadata for this parameter (e.g. PII flags, ownership).
  final Map<String, dynamic> meta;

  /// List of operations supported by this parameter (e.g. set, increment).
  /// Only used for context properties.
  final List<String>? operations;

  /// Version when this parameter was added.
  final String? addedIn;

  /// Version when this parameter was deprecated.
  final String? deprecatedIn;

  @override
  String toString() => '$name: $type${isNullable ? '?' : ''}';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final collectionEquals = const DeepCollectionEquality().equals;

    return other is AnalyticsParameter &&
        other.name == name &&
        other.sourceName == sourceName &&
        other.codeName == codeName &&
        other.type == type &&
        other.isNullable == isNullable &&
        other.description == description &&
        collectionEquals(other.allowedValues, allowedValues) &&
        other.regex == regex &&
        other.minLength == minLength &&
        other.maxLength == maxLength &&
        other.min == min &&
        other.max == max &&
        collectionEquals(other.meta, meta) &&
        collectionEquals(other.operations, operations) &&
        other.addedIn == addedIn &&
        other.deprecatedIn == deprecatedIn;
  }

  @override
  int get hashCode {
    final deepHash = const DeepCollectionEquality().hash;

    return Object.hashAll([
      name,
      sourceName,
      codeName,
      type,
      isNullable,
      description,
      deepHash(allowedValues),
      regex,
      minLength,
      maxLength,
      min,
      max,
      deepHash(meta),
      deepHash(operations),
      addedIn,
      deprecatedIn,
    ]);
  }

  AnalyticsParameter copyWith({
    String? name,
    String? sourceName,
    String? codeName,
    String? type,
    bool? isNullable,
    String? description,
    List<dynamic>? allowedValues,
    String? regex,
    int? minLength,
    int? maxLength,
    num? min,
    num? max,
    Map<String, dynamic>? meta,
    List<String>? operations,
    String? addedIn,
    String? deprecatedIn,
  }) {
    return AnalyticsParameter(
      name: name ?? this.name,
      sourceName: sourceName ?? this.sourceName,
      codeName: codeName ?? this.codeName,
      type: type ?? this.type,
      isNullable: isNullable ?? this.isNullable,
      description: description ?? this.description,
      allowedValues: allowedValues ?? this.allowedValues,
      regex: regex ?? this.regex,
      minLength: minLength ?? this.minLength,
      maxLength: maxLength ?? this.maxLength,
      min: min ?? this.min,
      max: max ?? this.max,
      meta: meta ?? this.meta,
      operations: operations ?? this.operations,
      addedIn: addedIn ?? this.addedIn,
      deprecatedIn: deprecatedIn ?? this.deprecatedIn,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'source_name': sourceName,
      'code_name': codeName,
      'type': type,
      'is_nullable': isNullable,
      'description': description,
      'allowed_values': allowedValues,
      'regex': regex,
      'min_length': minLength,
      'max_length': maxLength,
      'min': min,
      'max': max,
      'meta': meta,
      'operations': operations,
      'added_in': addedIn,
      'deprecated_in': deprecatedIn,
    };
  }

  factory AnalyticsParameter.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return AnalyticsParameter(
      name: cast<String?>('name') ?? '',
      sourceName: cast<String?>('source_name'),
      codeName: cast<String?>('code_name') ?? '',
      type: cast<String?>('type') ?? '',
      isNullable: cast<bool?>('is_nullable') ?? false,
      description: cast<String?>('description'),
      allowedValues: map['allowed_values'] != null
          ? List<dynamic>.from(cast<Iterable>('allowed_values'))
          : null,
      regex: cast<String?>('regex'),
      minLength: cast<num?>('min_length')?.toInt(),
      maxLength: cast<num?>('max_length')?.toInt(),
      min: cast<num?>('min'),
      max: cast<num?>('max'),
      meta: Map<String, dynamic>.from(cast<Map?>('meta') ?? const {}),
      operations: map['operations'] != null
          ? List<String>.from(cast<Iterable>('operations'))
          : null,
      addedIn: cast<String?>('added_in'),
      deprecatedIn: cast<String?>('deprecated_in'),
    );
  }

  String toJson() => json.encode(toMap());

  factory AnalyticsParameter.fromJson(String source) =>
      AnalyticsParameter.fromMap(json.decode(source) as Map<String, dynamic>);
}
